version: 2

sources:
  - name: raw_gz_data
    description: raw data greenweez
    tables:
      - name: product
        description: raw gz product data
      - name: sales
        description: raw gz sales data
      - name: ship
        description: raw gz shipping data
