version: 2

version: 2

sources:
  - name: raw_gz_data
    description: "Raw data from Greenweez"
    tables:
      - name: product
        description: "Product information from raw_gz_product"
        columns:
          - name: product_id
            description: "Unique identifier for each product (primary key)"
            tests:
              - unique
              - not_null
          - name: product_name
            description: "Name of the product"
          - name: purchase_price
            description: "Purchase price of the product"
      - name: sales
        description: "Sales data from raw_gz_sales"
        columns:
          - name: sales_id
            description: "Unique identifier for each sale (primary key)"
            tests:
              - unique
              - not_null
          - name: product_id
            description: "Foreign key linking to product_id"
          - name: quantity_sold
            description: "Number of units sold"
      - name: ship
        description: "Shipping data from raw_gz_ship"
        columns:
          - name: shipment_id
            description: "Unique identifier for each shipment (primary key)"
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: "Cost of shipping for the order"