version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Sales data of Greenweez. Each row represents a product_id found in each orders_id.
        columns:
          - name: date_date
            description: Date of purchase
          - name: orders_id
            description: Foreign key to the ship table
          - name: pdt_id
            description: Foreign key to the product table
          - name: revenue
            description: The amount paid by the customer to purchase the product. Revenue = quantity * selling_price
          - name: quantity
            description: The quantity of products purchased for a given order
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - orders_id
                - pdt_id

      - name: product
        identifier: raw_gz_product
        description: Products data of Greenweez
        columns:
          - name: products_id
            description: Primary key
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: Shipping data for Greenweez orders
        columns:
          - name: orders_id
            description: Primary key
            tests:
              - unique
              - not_null
