version: 2

sources:
  - name: raw_gz_data
    description: raw data greenweez
    tables:
      - name: product
        description: raw_gz_product
      - name: sales
        description: raw_gz_sales
      - name: ship
        description: raw_gz_ship
